name: Order Tracker Application

run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: push

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: This is my first github action yml
      - run: echo "This is my first github action yml"
      - name: list all the fils
      - run: ls
      - run: echo "ğŸ This job's status is ${{ job.status }}." 